default: &default
   dialect: postgres
   database: simple_buffalo_development
   user: sujiths
   password: ''
   host: 127.0.0.1
   pool: 5

development:
  <<: *default

test:
  <<: *default
  database: simple_buffalo_test

production:
   <<: *default
   database: simple_buffalo_production
